version: 0.0

os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /var/www/html/code
    mode: 744
    owner: knpay:apache
    type:
      - directory


hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies
      timeout: 600
      runas: root

    - location: /scripts/start_server
      timeout: 300
      runas: root

    - location: /scripts/stop_server
      timeout: 300
      runas: root


  AfterInstall:
     - location: /scripts/removefiles
       timeout: 300
       runas: root
